server:
  port: 8085

spring:
  # 配置数据源
  datasource:
    # JDBC配置
    url: jdbc:mysql://39.106.68.204:3306/vein_scan_system?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ENC(vcl4NF2E+Ztw2WXTTQWF0IKjUr1oTrEQflTXStztT1G3mqVZNefXhOEEuLjOU4OY)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化连接数
      initial-size: 5

  # 配置热部署
  devtools:
    restart:
      enabled: false

  redis:
    host: 39.106.68.204
    port: 6379
    password: ENC(qacsLkgYlAwbyrQG1xRwlKKiF9DGsvPQblU3zVKIbWuM65KdwOfPOvAXBS5tYfcw)

swagger:
  enabled: true
