# 服务器配置
server:
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8
  # 应用访问路径
  servlet:
    context-path: /

# 图像存储路径
image:
  infraredDirectoryOnWin: G:/test/infrared/
  ultrasoundDirectoryOnWin: G:/test/ultrasound/
  infraredDirectoryOnLinux: /tmp/vein_scan_dms/infrared/
  ultrasoundDirectoryOnLinux: /tmp/vein_scan_dms/ultrasound/
  enableAliyunOss: true

# Spring配置
spring:
  application:
    name: service_patient

  profiles:
    active: prod

  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      #单个文件大小限制
      max-file-size: 10MB
      #请求总文件大小限制
      max-request-size: 100MB

# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # MyBatis Mapper 所对应的 XML 文件位置，
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 配置实体类所在位置
  type-aliases-package: hiram.**.pojo.**
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0

token:
  minuteExpireTime: 1440

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI4GBjjUFnVEyyGYT7kkyh
      accessKeySecret: ENC(lj7v2E44aRwAQrWDH3NeouRHvTJ3YknGZIpQollJ2vWj6XDEwdHywE/WdeyBSZIavLzbPDkOyqhAf+uglFPCvg==)
      # bucket可以在控制台创建，也可以使用代码创建
      bucketName: vein-scan-system-010